# Generated by Django 4.2.6 on 2023-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.URLField(unique=True),
        ),
    ]
