# Generated by Django 4.2.6 on 2023-10-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0002_alter_urls_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=10),
        ),
    ]
