# Generated by Django 4.2.6 on 2023-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0003_alter_urls_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
